[channels]
main = "production"

[tasks.build]
workspace_batchable = true
cargo = ["cargo", "build", "--locked"]

[tasks.publish]
cascade = "all"
autoapply = "inherit"
depends_on = ["build"]
cargo = ["cargo", "publish", "--locked"]
